VehicleProject.Web/Controllers/VehicleMakeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VehicleProject.Service;
using VehicleProject.Web.Models;
using VehicleProject.DAL;
using AutoMapper;
using PagedList;

namespace VehicleProject.Web.Controllers
{
    public class VehicleMakeController : Controller
    {
        private IVehicleMakeService _vehicleMakeService;
        private readonly IMapper _mapper;

        public VehicleMakeController(IVehicleMakeService vehicleMakeService, IMapper mapper)
        {
            _vehicleMakeService = vehicleMakeService;
            _mapper = mapper;
        }


        //create make
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(VehicleMakeVM makeModel)
        {
            var makeEntity = _mapper.Map<VehicleMakeVM, VehicleMakeEntity>(makeModel);
            _vehicleMakeService.CreateVehicleMake(makeEntity);
            if(makeEntity.MakeId != Guid.Empty)
            {
                return RedirectToAction("Index");
            }
            return View();
        }



        //Vehicle make list
        [HttpGet]
        public ActionResult Index(int? page, string sortTerm, string searchTerm)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            ViewBag.currentSort = sortTerm;
            ViewBag.currentSearch = searchTerm;

            var pagedVehicleMakeEntities = _vehicleMakeService.GetPagedVehicleMakes(pageSize, pageNumber, sortTerm, searchTerm);
            var tempVehicleMakeModels = _mapper.Map<IEnumerable<VehicleMakeEntity>, IEnumerable<VehicleMakeVM>>(pagedVehicleMakeEntities.ToArray());
            var pagedVehicleMakeModels = new StaticPagedList<VehicleMakeVM>(tempVehicleMakeModels, pagedVehicleMakeEntities.GetMetaData());
            return View(pagedVehicleMakeModels);
        }

        //sngle vehicle make
        [HttpGet]
        public ActionResult Details(Guid id)
        {
            var makeEntity = _vehicleMakeService.GetVehicleMake(id);
            var makeModel = _mapper.Map<VehicleMakeEntity, VehicleMakeVM>(makeEntity);
            return View(makeModel);
        }

        //update make
        [HttpGet]
        public ActionResult Update(Guid id)
        {
            var makeEntity = _vehicleMakeService.GetVehicleMake(id);
            var makeModel = _mapper.Map<VehicleMakeEntity, VehicleMakeVM>(makeEntity);
            return View(makeModel);
        }

        [HttpPost]
        public ActionResult Update(VehicleMakeVM makeModel)
        {
            var makeEntity = _mapper.Map<VehicleMakeVM, VehicleMakeEntity>(makeModel);
            _vehicleMakeService.UpdateVehicleMake(makeEntity);
            return RedirectToAction("Index");
        }

        //delete make
        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            var makeEntity = _vehicleMakeService.GetVehicleMake(id);
            var makeModel = _mapper.Map<VehicleMakeEntity, VehicleMakeVM>(makeEntity);
            return View(makeModel);

        }
        [HttpPost]
        public ActionResult Delete(VehicleMakeVM makeModel)
        {
            var makeEntity = _mapper.Map<VehicleMakeVM, VehicleMakeEntity>(makeModel);
            _vehicleMakeService.DeleteVehicleMake(makeEntity);
            return RedirectToAction("Index");
        }

    }
}

VehicleProject.Web/Views/VehicleMake/Create.cshtml
@model VehicleProject.Web.Models.VehicleMakeVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Create Make";
}

<div class="panel panel-primary">
    <div class="panel-heading">Create Make</div>
    <div class="panel-body">
        @using (Html.BeginForm())
            {
                <div class="form-gorup">
                    @Html.LabelFor(model => model.Name, new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-gorup">
                    @Html.LabelFor(model => model.Abbr, new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(model => model.Abbr, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-9"></div>
                    <div class="col-lg-3">
                        <input type="submit" value="Create" class="btn btn-success"/>
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
                    </div>
                </div>
            }
    </div>
</div>

VehicleProject.Web/Views/VehicleMake/Delete.cshtml
@model VehicleProject.Web.Models.VehicleMakeVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Delete Make";
}


<div class="panel panel-primary">
    <div class="panel-heading panel-head">Delete Make</div>
    <div class="panel-body">
        <div>
            <h3 class="text-danger">Are you sure you Want to delete this make and all it's models?</h3>
        </div>
        @using (Html.BeginForm())
        {
            <div>
                @Html.HiddenFor(model => model.Id)
                <div class="form-gorup">
                    @Html.LabelFor(model => model.Name, new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(model => model.Name, new { @readonly = "readonly", @class = "form-control" })
                    </div>
                </div>
                <div class="form-gorup">
                    @Html.LabelFor(model => model.Abbr, new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(model => model.Abbr, new { @readonly = "readonly", @class = "form-control" })
                    </div>
                </div>
            </div>



            <div class="form-group">
                <br />
                @Html.LabelFor(model =>model.MakeModels, new { @class="col-lg-3 control label"})
                <div class="col-lg-9"></div>
            </div>

            <div class="form-group">
                <table class="table">
                    <tr>                        

                        <td>
                            Model name
                        </td>
                        <td>
                            Model Abbreviation
                        </td>
                    </tr>
                    @foreach (var item in Model.MakeModels)
                    {
                        <tr>
                            <td>
                                @Html.HiddenFor(ModelItem => item.MakeId)
                                @Html.HiddenFor(ModelItem => item.Id)
                                @Html.HiddenFor(ModelItem => item.Make)
                                @Html.DisplayFor(ModelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(ModelItem => item.Abbr)
                            </td>
                        </tr>
                    }
                </table>
            </div>



            <div class="form-group">
                <div class="col-lg-1"></div>
                <div class="col-lg-9">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success" })
                </div>
            </div>
        }
    </div>
</div>

VehicleProject.Web/Views/VehicleMake/Details.cshtml
@model VehicleProject.Web.Models.VehicleMakeVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Make Details";
}


<div class="panel panel-primary">
    <div class="panel-heading panel-head">Make Details</div>
    <div class="panel-body">
        <form class="form-horizontal">
            <div>
                <div class="form-gorup">
                    @Html.LabelFor(model => model.Id, new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(model => model.Id, new { @readonly = "readonly", @class = "form-control" })
                    </div>
                </div>
                <div class="form-gorup">
                    @Html.LabelFor(model => model.Name, new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(model => model.Name, new { @readonly = "readonly", @class = "form-control" })
                    </div>
                </div>
                <div class="form-gorup">
                    @Html.LabelFor(model => model.Abbr, new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(model => model.Abbr, new { @readonly = "readonly", @class = "form-control" })
                    </div>
                </div>
            </div>


            <div class="form-group">
                <br />
                @Html.LabelFor(model => model.MakeModels, new { @class = "col-lg-3 control-label" }) 
                <div class="col-lg-9"></div>
            </div>

            <div class="form-group">
                <table class="table">
                    <tr>

                        <td>
                            Model name
                        </td>
                        <td>
                            Model Abbreviation
                        </td>
                    </tr>
                    @foreach (var item in Model.MakeModels)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(ModelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(ModelItem => item.Abbr)
                            </td>
                        </tr>
                    }
                </table>
            </div>


            <div class="form-group">
                <div class="col-lg-3"></div>
                <div class="col-lg-9">
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success" })
                </div>
            </div>
        </form>
    </div>
</div>

VehicleProject.Web/Views/VehicleMake/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<VehicleProject.Web.Models.VehicleMakeVM>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Vehicle Make Index";
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<div class="panel panel-primary">
    <div class="panel-heading panel-head">Vehicle Make Index</div>

    <div class="panel-body">
        <a href="@Url.Action("Create")" class="btn btn-success">
            <span class="glyphicon glyphicon-plus"></span>Vehicle Make
        </a>
        <hr />

        <div>
            @using (Html.BeginForm("Index", "VehicleMake", new { sortTerm = ViewBag.currentSort }, FormMethod.Get))
            {
                @Html.Hidden("sortTerm", (string)ViewBag.currentSort);
                <div class="form-group">
                    <div class="col-lg-2">
                    Search: 
                    </div>
                    <div class="col-lg-3">
                    @Html.TextBox("searchTerm", ViewBag.currentSearch as string, new { @class = "form-control" })
                    </div>
                    <div class="col-lg-7">
                    <input type="submit" value="Search" class="btn btn-default" />
                    </div>
                </div>
            }
        </div>

        <table class="table">
            <tr>
                <th>
                    Make Id
                </th>
                <th>
                    Make Name
                    @Html.ActionLink(" ", "Index", new { sortTerm = "ByNameAscending", searchTerm = ViewBag.currentSearch }, new { @class = "glyphicon glyphicon-arrow-down" })
                    @Html.ActionLink(" ", "Index", new { sortTerm = "ByNameDescending", searchTerm = ViewBag.currentSearch }, new { @class = "glyphicon glyphicon-arrow-up" })
                </th>
                <th>
                    Make Abbreviation
                </th>
                <th>
                    Action
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(ModelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.Abbr)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Update", new { id = item.Id }, new { @class = "btn btn-success" }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-primary" })
                    </td>
                </tr>
            }
        </table>


    </div>
</div>


<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
new { page, sortTerm = ViewBag.CurrentSort}))

VehicleProject.Web/Views/VehicleMake/Update.cshtml
@model VehicleProject.Web.Models.VehicleMakeVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Update Make";
}

<div class="panel panel-primary">
    <div class="panel-heading">Update Make</div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
                <div class="form-gorup">
                    @Html.LabelFor(model => model.Id, new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(model => model.Id, new { @class = "form-control", @readonly="readonly" })
                    </div>
                </div>

                <div class="form-gorup">
                    @Html.LabelFor(model => model.Name, new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-gorup">
                    @Html.LabelFor(model => model.Abbr, new { @class = "col-sm-3 control-label" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(model => model.Abbr, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-9"></div>
                    <div class="col-lg-3">
                        <input type="submit" value="Update" class="btn btn-success" />
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
                    </div>
                </div>
        }
    </div>
</div>