VehicleProject.Web/Controllers/VehicleModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VehicleProject.Service;
using VehicleProject.Web.Models;
using VehicleProject.DAL;
using PagedList;
using AutoMapper;

namespace VehicleProject.Web.Controllers
{
    public class VehicleModelController : Controller
    {
        private IVehicleModelService _vehicleModelService;
        private IVehicleMakeService _vehicleMakeService;
        private readonly IMapper _mapper;
        public VehicleModelController(IVehicleModelService vehicleModelService, IVehicleMakeService vehicleMakeService, IMapper mapper)
        {
            _vehicleMakeService = vehicleMakeService;
            _vehicleModelService = vehicleModelService;
            _mapper = mapper;
        }

        public SelectList PopulateDropDown()
        {
            var vehicleMakeEntities = _vehicleMakeService.GetAll();
            var dropDownEntities = new List<SelectListItem>();

            dropDownEntities.Add(new SelectListItem
            {
                Value = "",
                Text = " ",
                Selected = true
            });

            foreach (var item in vehicleMakeEntities)
            {
                dropDownEntities.Add(new SelectListItem
                {
                    Value = item.MakeId.ToString(),
                    Text = item.MakeName
                });
            }
            return new SelectList(dropDownEntities, "Value", "Text");
        }



        //create model
        [HttpGet]
        public ActionResult Create()
        {
            //dropdownlist for make selection, selects Id
            ViewBag.dropDownListOptions = PopulateDropDown();
            return View();
        }

        [HttpPost]
        public ActionResult Create(VehicleModelVM modelModel)
        {
            VehicleModelEntity modelEntity = new VehicleModelEntity();

            modelEntity = _mapper.Map<VehicleModelVM, VehicleModelEntity>(modelModel);
            _vehicleModelService.CreateVehicleModel(modelEntity, modelEntity.VehicleMakeId);

            if (modelEntity.ModelId != Guid.Empty)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        //vehicle Model list
        [HttpGet]
        public ActionResult Index(int? page, string filterId, string sortTerm, string searchTerm)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            ViewBag.currentSort = sortTerm;
            ViewBag.currentFilter = filterId;
            ViewBag.currentSearch = searchTerm;

            //dropdownlist for filtering
            ViewBag.dropDownListOptions = PopulateDropDown();

            //fetching data, returning sorted/filtered/paged result
            var pagedVehicleModelEntities = _vehicleModelService.GetPagedVehicleModels(pageSize, pageNumber, filterId, sortTerm, searchTerm);
            var tempVehicleModelModels = _mapper.Map<IEnumerable<VehicleModelEntity>, IEnumerable<VehicleModelVM>>(pagedVehicleModelEntities.ToArray());
            var pagedVehicleModelModels = new StaticPagedList<VehicleModelVM>(tempVehicleModelModels, pagedVehicleModelEntities.GetMetaData());
            return View(pagedVehicleModelModels);
        }

        //sngle vehicle model
        [HttpGet]
        public ActionResult Details(Guid id)
        {
            var modelEntity = _vehicleModelService.GetVehicleModel(id);
            var makeEntity = _vehicleMakeService.GetVehicleMake(modelEntity.VehicleMakeId);
            modelEntity.VehicleMake = makeEntity;
            var modelModel = _mapper.Map<VehicleModelEntity, VehicleModelVM>(modelEntity);
            return View(modelModel);
        }

        //update model
        [HttpGet]
        public ActionResult Update(Guid id)
        {
            var modelEntity = _vehicleModelService.GetVehicleModel(id);
            var modelModel = _mapper.Map<VehicleModelEntity, VehicleModelVM>(modelEntity);
            return View(modelModel);
        }

        [HttpPost]
        public ActionResult Update(VehicleModelVM modelModel)
        {
            var modelEntity = _mapper.Map<VehicleModelVM, VehicleModelEntity>(modelModel);
            _vehicleModelService.UpdateVehicleModel(modelEntity);
            return RedirectToAction("Index");
        }

        //delete model
        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            var modelEntity = _vehicleModelService.GetVehicleModel(id);
            var modelModel = _mapper.Map<VehicleModelEntity, VehicleModelVM>(modelEntity);
            return View(modelModel);

        }
        [HttpPost]
        public ActionResult Delete(VehicleModelVM modelModel)
        {
            var modelEntity = _mapper.Map<VehicleModelVM, VehicleModelEntity>(modelModel);
            _vehicleModelService.DeleteVehicleModel(modelEntity);
            return RedirectToAction("Index");
        }

    }
}

VehicleProject.Web/Views/VehicleModel/Create.cshtml
@model VehicleProject.Web.Models.VehicleModelVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Create Model";
}

<div class="panel panel-primary">
    <div class="panel-heading panel-head">Create Model</div>
    <div class="panel-body">
        @using (Html.BeginForm())
            {
                <div class="form-gorup">
                    <div class="col-lg-3">
                    Vehicle Make
                    </div>
                    <div class="col-lg-9">
                        @Html.DropDownListFor(model =>model.MakeId, ViewBag.dropDownListOptions as SelectList, new { @class = "btn btn-dropdown dropdown-toggle" })
                    </div>
                </div>

                <div class="form-gorup">
                    @Html.LabelFor(model => model.Name, new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-gorup">
                    @Html.LabelFor(model => model.Abbr, new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(model => model.Abbr, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-1"></div>
                    <div class="col-lg-9">
                        <input type="submit" value="Create" class="btn btn-danger" />
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success" })
                    </div>
                </div>
            }
    </div>
</div>

VehicleProject.Web/Views/VehicleModel/Delete.cshtml
@model VehicleProject.Web.Models.VehicleModelVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Delete Model";
}


<div class="panel panel-primary">
    <div class="panel-heading panel-head">Delete Model</div>
    <div class="panel-body">
        <div>
            <h3 class="text-danger">Are you sure you Want to delete this model?</h3>
        </div>
            @using (Html.BeginForm())
            {
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.MakeId)
                <div class="form-gorup">
                    @Html.LabelFor(model => model.Make.Name, new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(model => model.Make.Name , new { @readonly="readonly", @class = "form-control" })
                    </div>
                </div>

                <div class="form-gorup">
                    @Html.LabelFor(model => model.Name , new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(model => model.Name, new { @readonly="readonly", @class = "form-control" })
                    </div>
                </div>

                <div class="form-gorup">
                    @Html.LabelFor(model => model.Abbr, new { @class = "col-lg-3 control-label" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(model => model.Abbr, new { @readonly="readonly", @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-1"></div>
                    <div class="col-lg-9">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success" })
                    </div>
                </div>
            }
    </div>
</div>

VehicleProject.Web/Views/VehicleModel/Details.cshtml
@model VehicleProject.Web.Models.VehicleModelVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Model Details";
}


<div class="panel panel-primary">
    <div class="panel-heading panel-head">Model details</div>
    <div class="panel-body">
@using (Html.BeginForm())
            {
        
            <div class="form-gorup">
                @Html.LabelFor(model => model.Id, new { @class = "col-lg-3 control-label" })
                <div class="col-lg-9">
                    @Html.TextBoxFor(model => model.Id, new { @readonly = "readonly", @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Make.Name, new { @class = "col-lg-3 control-label" })
                <div class="col-lg-9">
                    @Html.TextBoxFor(model => model.Make.Name, new { @readonly = "readonly", @class = "form-control" })
                </div>
            </div>

            <div class="form-gorup">
                @Html.LabelFor(model => model.Name, new { @class = "col-lg-3 control-label" })
                <div class="col-lg-9">
                    @Html.TextBoxFor(model => model.Name, new { @readonly = "readonly", @class = "form-control" })
                </div>
            </div>

            <div class="form-gorup">
                @Html.LabelFor(model => model.Abbr, new { @class = "col-lg-3 control-label" })
                <div class="col-lg-9">
                    @Html.TextBoxFor(model => model.Abbr, new { @readonly = "readonly", @class = "form-control" })
                </div>
            </div>


                <div class="form-group">
                    <div class="col-lg-1"></div>
                    <div class="col-lg-9">
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success" })
                    </div>
                </div>
            }


    </div>
</div>

VehicleProject.Web/Views/VehicleModel/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<VehicleProject.Web.Models.VehicleModelVM>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Vehicle Model Index";
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<div class="panel panel-primary">
    <div class="panel-heading panel-head">Vehicle Model Index</div>

    <div class="panel-body">

        <a href="@Url.Action("Create")" class="btn btn-success">
            <span class="glyphicon glyphicon-plus"></span>Vehicle Model
        </a>

        <hr/>
        <div>
            @using (Html.BeginForm("Index", "VehicleModel", FormMethod.Get))
            {
                @Html.Hidden("sortTerm", (string)ViewBag.currentSort);
                @Html.Hidden("filterId", (string)ViewBag.currentFilter);
                <div class="form-group">
                    <div class="col-lg-2">
                    Search: 
                    </div>
                    <div class="col-lg-3">
                    @Html.TextBox("searchTerm", ViewBag.currentSearch as string, new { @class = "form-control"})
                    </div>
                    <div class="col-lg-7">
                        <input type="submit" value="Search" class="btn btn-default" />
                    </div>
                </div>
            }
        </div>
        <hr />

        <div>
            @using (Html.BeginForm("Index", "VehicleModel", FormMethod.Get))
            {
                @Html.Hidden("sortTerm", (string)ViewBag.currentSort);
                @Html.Hidden("searchTerm", (string)ViewBag.currentSearch);
                <div class="form-group">
                    <div class="col-lg-2">
                      Filter By Make:
                    </div>
                    <div class="col-lg-3">
                    @Html.DropDownList("filterId", ViewBag.dropDownListOptions as SelectList, new { @class = "form-control" })              
                    </div>
                    <div class="col-lg-7">
                        <input type="submit" value="Apply Filter" class="btn btn-default" />
                    </div>
                </div>
            }
        </div>
        
        <table class="table">
            <tr>
                <th>                    
                    Model ID
                </th>
                <th>
                    Make Name
                    @Html.ActionLink(" ", "Index", new { sortTerm = "ByMakeNameAscending", filterId = ViewBag.currentFilter, searchTerm = ViewBag.currentSearch }, new { @class = "glyphicon glyphicon-arrow-down" })
                    @Html.ActionLink(" ", "Index", new { sortTerm = "ByMakeNameDescending", filterId = ViewBag.currentFilter, searchTerm = ViewBag.currentSearch }, new { @class = "glyphicon glyphicon-arrow-up" })
                </th>
                <th>
                    Model Name
                    @Html.ActionLink(" ", "Index", new { sortTerm = "ByNameAscending", filterId = ViewBag.currentFilter, searchTerm = ViewBag.currentSearch }, new { @class = "glyphicon glyphicon-arrow-down" })
                    @Html.ActionLink(" ", "Index", new { sortTerm = "ByNameDescending", filterId = ViewBag.currentFilter, searchterm = ViewBag.currentSearch }, new { @class = "glyphicon glyphicon-arrow-up" })
                </th>
                <th>
                    Model Abbreviation
                </th>
                <th>
                    Action
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(ModelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.Make.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.Abbr)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Update", new { id = item.Id }, new { @class = "btn btn-success" }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-primary" })
                    </td>
                </tr>
            }
        </table>
    </div>
</div>


<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
new { page, filterId = ViewBag.currentFilter, sortTerm = ViewBag.currentSort, searchTerm = ViewBag.currentSearch}))

VehicleProject.Web/Views/VehicleModel/Update.cshtml
@model VehicleProject.Web.Models.VehicleModelVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Update Model";
}


<div class="panel panel-primary">
    <div class="panel-heading panel-head">Update Model</div>
    <div class="panel-body">
@using (Html.BeginForm())
            {

            @Html.HiddenFor(model => model.MakeId)

            <div class="form-gorup">
                @Html.LabelFor(model => model.Id, new { @class = "col-lg-3 control-label" })
                <div class="col-lg-9">
                    @Html.TextBoxFor(model => model.Id, new { @readonly="readonly", @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Make.Name, new { @class = "col-lg-3 control-label" })
                <div class="col-lg-9">
                    @Html.TextBoxFor(model => model.Make.Name, new { @readonly="readonly", @class = "form-control" })
                </div>
            </div>

            <div class="form-gorup">
                @Html.LabelFor(model => model.Name, new { @class = "col-lg-3 control-label" })
                <div class="col-lg-9">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-gorup">
                @Html.LabelFor(model => model.Abbr, new { @class = "col-lg-3 control-label" })
                <div class="col-lg-9">
                    @Html.TextBoxFor(model => model.Abbr, new { @class = "form-control" })
                </div>
            </div>


                <div class="form-group">
                    <div class="col-lg-1"></div>
                    <div class="col-lg-9">
                        <input type="submit" value="Update" class="btn btn-danger" />
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success" })
                    </div>
                </div>
            }
    </div>
</div>